[package]
name = "tmplrust"
version = "0.1.1"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[[bin]]
name = "tmplrust"
path = "src/main.rs"

[dependencies]
