name: Release

on:
  release:
    types: [created]

permissions:
  contents: write

jobs:
  publish:
    strategy:
      matrix:
        os:
          - ubuntu-latest
          - windows-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Publish ${{ matrix.os }}
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: tmplrust
          archive: $bin-$tag-$target
          include: LICENSE,README.md
          token: ${{ secrets.GITHUB_TOKEN }}

  publish-cross-compiled:
    strategy:
      matrix:
        include:
          - target: aarch64-unknown-linux-gnu
            os: ubuntu-latest
          - target: aarch64-apple-darwin
            os: macos-latest
    runs-on: ${{ matrix.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Install cross-compilation tools
        uses: taiki-e/setup-cross-toolchain-action@v1
        with:
          target: ${{ matrix.target }}
      - name: Publish ${{ matrix.os }}
        uses: taiki-e/upload-rust-binary-action@v1
        with:
          bin: tmplrust
          target: ${{ matrix.target }}
          archive: $bin-$tag-$target
          include: LICENSE,README.md
          token: ${{ secrets.GITHUB_TOKEN }}
